# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Detector_Plugin
                                 A QGIS plugin
 This plugin will detect dry patches of land
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-12-11
        copyright            : (C) 2023 by Vanisha B
        email                : vanishaburagohain@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import sys
import os

# Add the path to your plugin directory to sys.path
sys.path.append(os.path.dirname(os.path.realpath(__file__)))

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Detector_Plugin class from file Detector_Plugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    try:
        from .detector import Detector_Plugin
        return Detector_Plugin(iface)
    except Exception as e:
        import traceback
        traceback.print_exc()
        raise ImportError(f"Error loading Detector_Plugin: {e}")

